name: Install gettext
on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: "1"

jobs:
  ci:
    name: Install gettext
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target: ["Windows"]
        include:
          - target: "Windows"
            output-format: "app"
            runs-on: "windows-latest"

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
          scoop bucket add main
          scoop install main/gettext
          msgfmt --version
        shell: pwsh
