name: Install gettext
on:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  ci:
    name: Install gettext
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gettext on Windows
        run: |
          iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
          scoop bucket add main
          scoop install main/gettext
          msgfmt --version
        shell: pwsh
