name: Install gettext matrix
on:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  ci:
    name: Install gettext
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target: ["Windows", "macOS"]
        include:
          - target: "Windows"
            output-format: "app"
            runs-on: "windows-latest"

          - target: "macOS"
            output-format: "app"
            runs-on: "macos-latest"

    steps:
      - uses: actions/checkout@v4
      - if: matrix.target == 'Windows'
        name: Install gettext on Windows
        run: |
          iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
          scoop bucket add main
          scoop install main/gettext
          msgfmt --version
        shell: pwsh
      - if: matrix.target == 'macOS'
        name: Install gettext on macOS
        run: |
          brew install gettext
          msgfmt --version
